"""init_v3_clean_data_protocol_io_key

Revision ID: 2414c5623620
Revises: 75222cc60488
Create Date: 2024-09-23 16:49:30.583339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2414c5623620'
down_revision = '75222cc60488'
branch_labels = None
depends_on = None


def upgrade():


    with op.batch_alter_table('clean_data_current_protocol', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index('ix_clean_data_current_protocol_id')

    with op.batch_alter_table('clean_data_protocol_io', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index('ix_clean_data_protocol_io_id')



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('clean_data_protocol_io', schema=None) as batch_op:
        batch_op.create_index('ix_clean_data_protocol_io_id', ['id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.StringUUID(),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('clean_data_current_protocol', schema=None) as batch_op:
        batch_op.create_index('ix_clean_data_current_protocol_id', ['id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.StringUUID(),
               type_=sa.String(length=255),
               existing_nullable=False)


    # ### end Alembic commands ###
