"""add_create_time_update_time_change_protocol_io_original_data_id_to_string

Revision ID: 2f8efb05420d
Revises: 8b245e20dcd8
Create Date: 2024-09-25 16:04:54.821039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f8efb05420d'
down_revision = '8b245e20dcd8'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('clean_data_current_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('clean_data_protocol_io', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('original_data_current_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))

    with op.batch_alter_table('original_data_protocol_io', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('original_resource_current_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))

    with op.batch_alter_table('original_resource_protocol_io', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('original_resource_protocol_io', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.drop_column('update_time')
        batch_op.drop_column('create_time')

    with op.batch_alter_table('original_resource_current_protocol', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.drop_column('update_time')
        batch_op.drop_column('create_time')

    with op.batch_alter_table('original_data_protocol_io', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('update_time')
        batch_op.drop_column('create_time')

    with op.batch_alter_table('original_data_current_protocol', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.drop_column('update_time')
        batch_op.drop_column('create_time')

    with op.batch_alter_table('clean_data_protocol_io', schema=None) as batch_op:
        batch_op.drop_column('update_time')
        batch_op.drop_column('create_time')

    with op.batch_alter_table('clean_data_current_protocol', schema=None) as batch_op:
        batch_op.drop_column('update_time')
        batch_op.drop_column('create_time')


