"""adjust_current_protocol_table

Revision ID: 30c874bfb134
Revises: a51e5fa201b1
Create Date: 2024-10-12 14:25:23.014485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30c874bfb134'
down_revision = 'a51e5fa201b1'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('clean_data_current_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_backup', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('relates_backup', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('author_list_backup', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('abstract_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('file_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('keywords_backup', sa.JSON(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)
        batch_op.drop_column('content1')
        batch_op.drop_column('content2')
        batch_op.drop_column('abstract')
        batch_op.drop_column('content3')
        batch_op.drop_column('img_length')



    with op.batch_alter_table('original_data_current_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords_backup', sa.JSON(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=False)
        batch_op.drop_index('meta_article_idx')
        batch_op.drop_column('content2')
        batch_op.drop_column('content1')

    with op.batch_alter_table('original_data_nature_protocol', schema=None) as batch_op:
        batch_op.alter_column('issue',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
        batch_op.alter_column('volume',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)

    with op.batch_alter_table('original_resource_current_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('md5', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('original_resource_current_protocol', schema=None) as batch_op:
        batch_op.drop_column('md5')
        batch_op.drop_column('description')

    with op.batch_alter_table('original_data_nature_protocol', schema=None) as batch_op:
        batch_op.alter_column('volume',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
        batch_op.alter_column('issue',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    with op.batch_alter_table('original_data_current_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content1', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content2', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_index('meta_article_idx', ['doi'], unique=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('keywords_backup')

    with op.batch_alter_table('clean_data_nature_protocol', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clean_data_nature_protocol_doi'))

    with op.batch_alter_table('clean_data_current_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_length', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content3', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('abstract', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content2', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content1', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('keywords_backup')
        batch_op.drop_column('file_info')
        batch_op.drop_column('content')
        batch_op.drop_column('abstract_text')
        batch_op.drop_column('author_list_backup')
        batch_op.drop_column('relates_backup')
        batch_op.drop_column('reference_backup')


