"""adjust_description_2_text

Revision ID: 5e03f52fb244
Revises: eb5510896626
Create Date: 2024-10-13 21:28:47.836560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e03f52fb244'
down_revision = 'eb5510896626'
branch_labels = None
depends_on = None


def upgrade():


    with op.batch_alter_table('original_resource_current_protocol', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('original_resource_nature_protocol', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('original_resource_nature_protocol', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)

    with op.batch_alter_table('original_resource_current_protocol', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)


