"""adjust_current_protocol_table_v2

Revision ID: 63a929fce964
Revises: 30c874bfb134
Create Date: 2024-10-12 14:42:15.275193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63a929fce964'
down_revision = '30c874bfb134'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('clean_data_current_protocol', schema=None) as batch_op:
        batch_op.drop_column('keywords')
        batch_op.drop_column('relates')
        batch_op.drop_column('author_list')
        batch_op.drop_column('reference')



    with op.batch_alter_table('original_data_current_protocol', schema=None) as batch_op:
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('original_data_current_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))



    with op.batch_alter_table('clean_data_current_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('author_list', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('relates', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('keywords', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))


