"""add_protocol_io_title_1024

Revision ID: 6a2a2a3031f8
Revises: 5e03f52fb244
Create Date: 2024-10-25 22:55:36.007466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a2a2a3031f8'
down_revision = '5e03f52fb244'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('clean_data_protocol_io', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clean_data_protocol_io', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)


