"""init_v2

Revision ID: 75222cc60488
Revises: 2bcedbbb8915
Create Date: 2024-09-23 14:34:17.479524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75222cc60488'
down_revision = '2bcedbbb8915'
branch_labels = None
depends_on = None


def upgrade():

    op.create_table('original_data_protocol_io',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('access', sa.JSON(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('before_start', sa.Text(), nullable=True),
    sa.Column('created_on', sa.Integer(), nullable=True),
    sa.Column('creator', sa.JSON(), nullable=True),
    sa.Column('cross_cloud_origin', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('ethics_statement', sa.Text(), nullable=True),
    sa.Column('fork_id', sa.String(length=255), nullable=True),
    sa.Column('guid', sa.String(length=255), nullable=True),
    sa.Column('guidelines', sa.Text(), nullable=True),
    sa.Column('image', sa.JSON(), nullable=True),
    sa.Column('is_content_confidential', sa.Boolean(), nullable=True),
    sa.Column('is_content_warning', sa.Boolean(), nullable=True),
    sa.Column('is_doi_reserved', sa.Boolean(), nullable=True),
    sa.Column('is_in_pending_publishing', sa.Boolean(), nullable=True),
    sa.Column('is_in_transfer', sa.Boolean(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('is_research', sa.Boolean(), nullable=True),
    sa.Column('is_subprotocol', sa.Boolean(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('journal', sa.JSON(), nullable=True),
    sa.Column('protocol_id', sa.String(length=255), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('manuscript_citation', sa.Text(), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.Column('materials_text', sa.Text(), nullable=True),
    sa.Column('protocol_references', sa.Text(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('published_on', sa.Integer(), nullable=True),
    sa.Column('reserved_doi', sa.String(length=255), nullable=True),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('status', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_html', sa.Text(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('units', sa.JSON(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('version_class', sa.Integer(), nullable=True),
    sa.Column('version_data', sa.Text(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('version_uri', sa.Text(), nullable=True),
    sa.Column('versions', sa.JSON(), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('original_data_protocol_io')

    # ### end Alembic commands ###
