"""clean_data_add-figures

Revision ID: 825efd1a6cee
Revises: 6a2a2a3031f8
Create Date: 2024-10-29 11:56:02.500776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '825efd1a6cee'
down_revision = '6a2a2a3031f8'
branch_labels = None
depends_on = None


def upgrade():


    with op.batch_alter_table('clean_data_current_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('figures', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('clean_data_nature_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('figures', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.create_index(batch_op.f('ix_clean_data_nature_protocol_doi'), ['doi'], unique=True)

    with op.batch_alter_table('clean_data_protocol_io', schema=None) as batch_op:
        batch_op.add_column(sa.Column('figures', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clean_data_protocol_io', schema=None) as batch_op:
        batch_op.drop_column('figures')

    with op.batch_alter_table('clean_data_nature_protocol', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clean_data_nature_protocol_doi'))
        batch_op.drop_column('figures')

    with op.batch_alter_table('clean_data_current_protocol', schema=None) as batch_op:
        batch_op.drop_column('figures')


