"""test

Revision ID: 8b13ea4e86db
Revises: c29b97d850f2
Create Date: 2024-10-08 17:42:11.129070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b13ea4e86db'
down_revision = 'c29b97d850f2'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('original_resource_nature_protocol', schema=None) as batch_op:
        batch_op.drop_column('oss_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('original_resource_nature_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oss_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))


    # ### end Alembic commands ###
