"""init_v4_task_change_date_time

Revision ID: 8b245e20dcd8
Revises: 2414c5623620
Create Date: 2024-09-23 17:46:21.716941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b245e20dcd8'
down_revision = '2414c5623620'
branch_labels = None
depends_on = None


def upgrade():



    with op.batch_alter_table('datasets_task', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('datasets_task', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)


    # ### end Alembic commands ###
