"""add_issue_and_volume_to_original_data_nature_protocol

Revision ID: a2151aa3934c
Revises: 58ac8ca8bb76
Create Date: 2024-10-11 12:06:03.308436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2151aa3934c'
down_revision = '58ac8ca8bb76'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('original_data_nature_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('volume', sa.String(length=1024), nullable=True))



    # ### end Alembic commands ###


def downgrade():

    with op.batch_alter_table('original_data_nature_protocol', schema=None) as batch_op:
        batch_op.drop_column('volume')
        batch_op.drop_column('issue')


