"""create_nature_protocol_ralate_table

Revision ID: c29b97d850f2
Revises: 2f8efb05420d
Create Date: 2024-10-08 12:06:25.303887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c29b97d850f2'
down_revision = '2f8efb05420d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clean_data_nature_protocol',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.JSON(), nullable=True),
    sa.Column('author_list', sa.JSON(), nullable=True),
    sa.Column('abstract_text', sa.Text(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('volume', sa.String(length=255), nullable=True),
    sa.Column('issue', sa.String(length=255), nullable=True),
    sa.Column('publish_date', sa.String(length=255), nullable=True),
    sa.Column('file_info', sa.JSON(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )


    op.create_table('original_data_nature_protocol',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.String(length=1024), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('article_description', sa.Text(), nullable=True),
    sa.Column('uri', sa.String(length=1024), nullable=True),
    sa.Column('published_on', sa.BigInteger(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('original_resource_nature_protocol',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('original_path', sa.String(length=1024), nullable=True),
    sa.Column('original_name', sa.String(length=1024), nullable=True),
    sa.Column('md5', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('oss_path', sa.String(length=1024), nullable=True),
    sa.Column('oss_bucket', sa.String(length=256), nullable=True),
    sa.Column('oss_name', sa.String(length=256), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=255), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('original_resource_nature_protocol')
    op.drop_table('original_data_nature_protocol')

    op.drop_table('clean_data_nature_protocol')
    # ### end Alembic commands ###
