"""adjust_current_protocol_table_v3

Revision ID: eb5510896626
Revises: 63a929fce964
Create Date: 2024-10-12 14:45:27.642959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb5510896626'
down_revision = '63a929fce964'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('clean_data_current_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('relates', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('author_list', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.JSON(), nullable=True))
        batch_op.drop_column('reference_backup')
        batch_op.drop_column('author_list_backup')
        batch_op.drop_column('relates_backup')
        batch_op.drop_column('keywords_backup')



    with op.batch_alter_table('original_data_current_protocol', schema=None) as batch_op:
        batch_op.alter_column('keywords_backup', new_column_name='keywords')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('original_data_current_protocol', schema=None) as batch_op:
        batch_op.alter_column('keywords', new_column_name='keywords_backup')



    with op.batch_alter_table('clean_data_current_protocol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords_backup', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('relates_backup', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('author_list_backup', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reference_backup', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('keywords')
        batch_op.drop_column('author_list')
        batch_op.drop_column('relates')
        batch_op.drop_column('reference')


