"""protocol_io_original_data__add-funders_acknowledgements

Revision ID: f3830d759163
Revises: 825efd1a6cee
Create Date: 2024-10-29 15:50:21.777200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3830d759163'
down_revision = '825efd1a6cee'
branch_labels = None
depends_on = None


def upgrade():


    with op.batch_alter_table('original_data_protocol_io', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funders', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('acknowledgements', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('original_data_protocol_io', schema=None) as batch_op:
        batch_op.drop_column('acknowledgements')
        batch_op.drop_column('funders')


